Config Api
asgErDe1inf12021/Projekt pull request #2
Opened 2021-06-14 09:06 UTC by Mari023

Make a public confic api and some (private) implementation

2021-06-18 10:15 UTC, slicktwig approved these changes

2021-06-21 08:31 UTC, Specktulatius requested changes

2021-06-21 08:31 UTC, Specktulatius commented on src/main/java/project/config/api/Serializable.java
> +    void readFrom(HashMap<String, Storage> map);
return the deserialized Object

2021-06-21 08:34 UTC, Specktulatius approved these changes

2021-06-21 08:35 UTC, merged